export enum ActionsEnum {
  CHANGE_PRESENTATION_TITLE = "CHANGE_PESENTATION_TITLE",
}

export enum SlidesActionEnum {
  GOTO_SLIDE = "GOTO_SLIDE",
  ADD_SLIDE = "ADD_SLIDE",
  DELETE_SLIDES = "DELETE_SLIDE",
  SET_SLIDES = "SET_SLIDES",
  CHANGE_ORDERS = "CHANGE_ORDERS",
  CHANGE_SLIDE_COLOR = "CHANGE_SLIDE_COLOR",
  CHANGE_BACKGROUND = "CHANGE_BACKGROUND",
}

export enum ElementsActionEnum {
  MOVE_ELEMENT = "MOVE_ELEMENT",
  ADD_ELEMENT = "ADD_ELEMENT",
  CHANDE_SCALE = "CHANDE_SCALE",
  SET_NEW_TEXT = "SET_NEW_TEXT",
  SET_NEW_FONT = "SET_NEW_FONT",
  SET_NEW_IMAGE = "SET_NEW_IMAGE",
  DELETE_ELEMENT = "DELETE_ELEMENT",
}

export enum ListOfSelectedEnum {
  ADD_SELECTED_ELEMENT = "ADD_SELECTED_ELEMENT",
  ADD_SELECTED_SLIDE = "ADD_SELECTED_SLIDE",
  INIT_SELECTED = "INIT_SELECTED",
}
